swagger: '2.0'
# Document information
info:
  $ref: ./info/index.yaml
# API host and basePath for testing requests
host: example.com
schemes:
  - http
  - https
basePath: /
# The list of modules and their short descriptions
tags:
  - name: Userfeedback
    description: The user feedback module
  - name: Advertisement
    description: The advertisement module
  - name: Admin
    description: Interface for provisioning and other administrative operations.
# References to the definitions, "global" parameters and paths
definitions:
  $ref: ./definitions/index.yaml
parameters:
  $ref: ./parameters/index.yaml
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
  contextAdminAuth:
    description: The API can be accessed via HTTP Basic Auth with context administrator credentials or reseller/master administrator credentials if MASTER_ACCOUNT_OVERRIDE is enabled.
    type: basic
paths:
  source: ./paths/
  