feature_name: Admin
properties:
    - key: MASTER_AUTHENTICATION_DISABLED
      description: |
        Disabling authentication for system calls like context/server etc. creation!
      
        <b>Attention</b>:  
        Only use this switch if you exactly know what you do!
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin", "Authentication"]
    - key: CONTEXT_AUTHENTICATION_DISABLED
      description: |
        Disabling authentication for context calls like user/group etc. creation!
        This also disables authentication for calls which a "normal" user can make
        like change his own data or get his own data!

        <b>Attention</b>:  
        Only use this switch if you exactly know what you do!
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin", "Authentication"]
    - key: USER_STORAGE
      description: |
        A OXUserStorageInterface implementation which should be used by the admin module.
      defaultValue: com.openexchange.admin.storage.mysqlStorage.OXUserMySQLStorage
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: GROUP_STORAGE
      description: |
        A OXGroupStorageInterface implementation which should be used by the admin module.
      defaultValue: com.openexchange.admin.storage.mysqlStorage.OXGroupMySQLStorage
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: RESOURCE_STORAGE
      description: |
        A OXResourceStorageInterface implementation which should be used by the admin module.
      defaultValue: com.openexchange.admin.storage.mysqlStorage.OXResourceMySQLStorage
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: CONCURRENT_JOBS
      description: |
        How many jobs should be executed concurrently.
      defaultValue: 2
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: MASTER_ACCOUNT_OVERRIDE
      description: |
        Set this to <code>true</code> if you want to be able to do all operations on any context using the
        login and password of the oxadminmaster account.
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminDaemon.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: DEFAULT_TIMEZONE
      description: |
        Specifies the default time zone to assume when creating a user
        and no explicit time zone is given in arguments.
      defaultValue: Europe/Berlin
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "Timezone", "User", "Provisioning"]
    - key: AUTO_TO_LOWERCASE_UID
      description: |
        This check will be performed on user names in case [[CHECK_USER_UID_FOR_NOT_ALLOWED_CHARS]] is set to <code>true</code>.
      defaultValue: "[$@%\\.+a-zA-Z0-9_-]"
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: CHECK_USER_UID_FOR_NOT_ALLOWED_CHARS
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User"]
    - key: UID_NUMBER_START
      description: |
        Set to a value greater than 0 to use the uidnumber feature.
      defaultValue: -1
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin"]
    - key: CHECK_USER_UID_FOR_NOT_ALLOWED_CHARS
      description: |
        This will check the user name using the check defined in [[CHECK_USER_UID_REGEXP]].
      defaultValue: true
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: CHECK_USER_UID_REGEXP
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User"]
    - key: CHECK_USER_UID_REGEXP
      description: |
        This check will be performed on user names in case [[CHECK_USER_UID_FOR_NOT_ALLOWED_CHARS]] is set to <code>true</code>.
      defaultValue: "[$@%\\.+a-zA-Z0-9_-]"
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: CHECK_USER_UID_FOR_NOT_ALLOWED_CHARS
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User"]
    - key: USERNAME_CHANGEABLE
      description: |
        WARNING: Changing the username might have impact on external systems like
        imap server that allows acls to be set. Imap ACLS usually use
        symbolic names so when changing the user name without changing
        the ACL breaks the ACL. open-xchange-admin will NOT change those
        ACLS, so DO NOT CHANGE THIS SETTING ON OX Express
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User"]
    - key: PRIMARY_MAIL_UNCHANGEABLE
      description: |
        Here you can set whether the primary mail address can be changed or not.
        If set to <code>false</code>, it is possible to change the primary mail address.
        Only change, if you know what you are doing (Outlook might
        not work anymore under certain circumstances).
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail"]
    - key: AVERAGE_USER_SIZE
      description: |
        The average file storage occupation for a user in MB.
      defaultValue: 100
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Filestore"]
    - key: ALLOW_CHANGING_QUOTA_IF_NO_FILESTORE_SET
      description: |
        Defines whether it is allowed to change the quota value for a user that has no individual file storage set.
        If set to <code>true</code> and the user has not yet an individual file storage set, an appropriate file storage gets
        assigned to the user. This implicitly includes to move the user's files from context file storage to that
        newly assigned file storage, which might be a long operation.
      defaultValue: false
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Filestore"]
    - key: SENT_MAILFOLDER_[language]
      description: |
        Default sent mail folder fallback for a specific language if not sent by rmi client. 
        The [language] variable must be replaced by an upper case language identifier. E.g. SENT_MAILFOLDER_DE_DE

        Default values:
          <ul>
           <li>SENT_MAILFOLDER_DE_DE=Gesendete Objekte</li>
           <li>SENT_MAILFOLDER_EN_GB=Sent Mai</li>
           <li>SENT_MAILFOLDER_EN_US=Sent Items</li>
           <li>SENT_MAILFOLDER_FR_FR=Objets envoy\u00e9s</li>
           <li>SENT_MAILFOLDER_NL_NL=Verzonden items</li>
           <li>SENT_MAILFOLDER_SV_SV=Skickat</li>
           <li>SENT_MAILFOLDER_ES_ES=Elementos enviados</li>
           <li>SENT_MAILFOLDER_JA_JP=\u9001\u4FE1\u6E08\u30A2\u30A4\u30C6\u30E0</li>
           <li>SENT_MAILFOLDER_PL_PL=Elementy wys\u0142ane</li>
           <li>SENT_MAILFOLDER_IT_IT=Posta inviata</li>
           <li>SENT_MAILFOLDER_ZH_CN=\u5df2\u53d1\u9001\u90ae\u4ef6</li>
           <li>SENT_MAILFOLDER_CS_CZ=Odeslan\u00e9 polo\u017eky</li>
           <li>SENT_MAILFOLDER_HU_HU=Elk\u00fcld\u00f6tt elemek</li>
           <li>SENT_MAILFOLDER_SK_SK=Odoslan\u00e9 polo\u017eky</li>
           <li>SENT_MAILFOLDER_LV_LV=Nos\u016Bt\u012Bt\u0101s vien\u012Bbas</li>
          </ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]
    - key: TRASH_MAILFOLDER_[language]
      description: |
        Default trash mail folder fallback if not sent by rmi client.
        The [language] variable must be replaced by an upper case language identifier. E.g. TRASH_MAILFOLDER_DE_DE

        Default values:
          <ul>
           <li>TRASH_MAILFOLDER_DE_DE=Papierkorb</li>
           <li>TRASH_MAILFOLDER_EN_GB=Trash</li>
           <li>TRASH_MAILFOLDER_EN_US=Trash</li>
           <li>TRASH_MAILFOLDER_FR_FR=Corbeille</li>
           <li>TRASH_MAILFOLDER_NL_NL=Prullenbak</li>
           <li>TRASH_MAILFOLDER_SV_SV=Papperskorgen</li>
           <li>TRASH_MAILFOLDER_ES_ES=Papelera</li>
           <li>TRASH_MAILFOLDER_JA_JP=\u524A\u9664\u6E08\u307F\u30A2\u30A4\u30C6\u30E0</li>
           <li>TRASH_MAILFOLDER_PL_PL=Kosz</li>
           <li>TRASH_MAILFOLDER_IT_IT=Cestino</li>
           <li>TRASH_MAILFOLDER_ZH_CN=\u5783\u573e\u7b52</li>
           <li>TRASH_MAILFOLDER_CS_CZ=Ko\u0161</li>
           <li>TRASH_MAILFOLDER_HU_HU=T\u00f6r\u00f6lt elemek</li>
           <li>TRASH_MAILFOLDER_SK_SK=K\u00f4\u0161</li>
           <li>TRASH_MAILFOLDER_LV_LV=Atkritumi</li>
          </ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]
    - key: DRAFTS_MAILFOLDER_[language]
      description: |
        Default drafts mail folder fallback if not sent by rmi client.
        The [language] variable must be replaced by an upper case language identifier. E.g. DRAFTS_MAILFOLDER_DE_DE

        Default values:
          <ul>
           <li>DRAFTS_MAILFOLDER_DE_DE=Entw\u00fcrfe</li>
           <li>DRAFTS_MAILFOLDER_EN_GB=Drafts</li>
           <li>DRAFTS_MAILFOLDER_EN_US=Drafts</li>
           <li>DRAFTS_MAILFOLDER_FR_FR=Brouillons</li>
           <li>DRAFTS_MAILFOLDER_NL_NL=Concepten</li>
           <li>DRAFTS_MAILFOLDER_SV_SV=Utkast</li>
           <li>DRAFTS_MAILFOLDER_ES_ES=Borradores</li>
           <li>DRAFTS_MAILFOLDER_JA_JP=\u4E0B\u66F8\u304D</li>
           <li>DRAFTS_MAILFOLDER_PL_PL=Szkice</li>
           <li>DRAFTS_MAILFOLDER_IT_IT=Bozze</li>
           <li>DRAFTS_MAILFOLDER_ZH_CN=\u8349\u7a3f</li>
           <li>DRAFTS_MAILFOLDER_CS_CZ=Koncepty</li>
           <li>DRAFTS_MAILFOLDER_HU_HU=Piszkozatok</li>
           <li>DRAFTS_MAILFOLDER_SK_SK=Rozp\u00edsan\u00e9</li>
           <li>DRAFTS_MAILFOLDER_LV_LV=Melnraksti</li>
          </ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]
    - key: SPAM_MAILFOLDER_[language]
      description: |
        Default spam mail folder fallback if not sent by rmi client.
        The [language] variable must be replaced by an upper case language identifier. E.g. SPAM_MAILFOLDER_DE_DE

        Default values:
          <ul>
           <li>SPAM_MAILFOLDER_DE_DE=Spam</li>
           <li>SPAM_MAILFOLDER_EN_GB=Spam</li>
           <li>SPAM_MAILFOLDER_EN_US=Spam</li>
           <li>SPAM_MAILFOLDER_FR_FR=Pourriel</li>
           <li>SPAM_MAILFOLDER_NL_NL=Spam</li>
           <li>SPAM_MAILFOLDER_SV_SV=Skr\u00E4ppost</li>
           <li>SPAM_MAILFOLDER_ES_ES=Correo no deseado</li>
           <li>SPAM_MAILFOLDER_JA_JP=\u8FF7\u60D1\u30E1\u30FC\u30EB</li>
           <li>SPAM_MAILFOLDER_PL_PL=Spam</li>
           <li>SPAM_MAILFOLDER_IT_IT=Posta Indesiderata</li>
           <li>SPAM_MAILFOLDER_ZH_CN=\u5783\u573e\u90ae\u4ef6</li>
           <li>SPAM_MAILFOLDER_CS_CZ=Spam</li>
           <li>SPAM_MAILFOLDER_HU_HU=Lev\u00e9lszem\u00e9t</li>
           <li>SPAM_MAILFOLDER_SK_SK=Spam</li>
           <li>SPAM_MAILFOLDER_LV_LV=M\u0113stules</li>
          </ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]
    - key: CONFIRMED_SPAM_MAILFOLDER_[language]
      description: |
        Default confirmed spam mail folder fallback if not sent by rmi client.
        The [language] variable must be replaced by an upper case language identifier. E.g. CONFIRMED_SPAM_MAILFOLDER_DE_DE

        Default values: 
          <ul>
            <li>CONFIRMED_SPAM_MAILFOLDER_DE_DE=confirmed-spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_EN_GB=confirmed-spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_EN_US=confirmed-spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_FR_FR=pourriel-confirme</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_NL_NL=bevestigde spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_SV_SV=bekr\u00E4ftad-skr\u00E4ppost</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_ES_ES=correo basura confirmado</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_JA_JP=\u8FF7\u60D1\u30E1\u30FC\u30EB\uFF08\u78BA\u8A8D\u6E08\uFF09</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_PL_PL=Potwierdzony spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_IT_IT=Posta indesiderata accertata</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_ZH_CN=\u5df2\u786e\u8ba4\u7684\u5783\u573e\u90ae\u4ef6</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_CS_CZ=Potvrzen\u00fd spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_HU_HU=Elfogadott k\u00e9retlen</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_SK_SK=Potvrden\u00fd spam</li>
            <li>CONFIRMED_SPAM_MAILFOLDER_LV_LV=Apstiprin\u0101ta "m\u0113stule"</li>
          </ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]
    - key: CONFIRMED_HAM_MAILFOLDER_[language]
      description: |
        Default confirmed ham mail folder fallback if not sent by rmi client.
        The [language] variable must be replaced by an upper case language identifier. E.g. CONFIRMED_HAM_MAILFOLDER__DE_DE

        Default values: 
          <ul>
           <li>CONFIRMED_HAM_MAILFOLDER_DE_DE=confirmed-ham</li>
           <li>CONFIRMED_HAM_MAILFOLDER_EN_GB=confirmed-ham</li>
           <li>CONFIRMED_HAM_MAILFOLDER_EN_US=confirmed-ham</li>
           <li>CONFIRMED_HAM_MAILFOLDER_FR_FR=non-pourriel-confirme</li>
           <li>CONFIRMED_HAM_MAILFOLDER_NL_NL=bevestigde ham</li>
           <li>CONFIRMED_HAM_MAILFOLDER_SV_SV=felaktigt-bekr\u00E4ftad-spam</li>
           <li>CONFIRMED_HAM_MAILFOLDER_ES_ES=correo leg\u00EDtimo confirmado</li>
           <li>CONFIRMED_HAM_MAILFOLDER_JA_JP=\u4E00\u822C\u30E1\u30FC\u30EB\uFF08\u78BA\u8A8D\u6E08\uFF09</li>
           <li>CONFIRMED_HAM_MAILFOLDER_PL_PL=Potwierdzony nie-spam</li>
           <li>CONFIRMED_HAM_MAILFOLDER_IT_IT=Posta attendibile accertata</li>
           <li>CONFIRMED_HAM_MAILFOLDER_ZH_CN=\u5df2\u786e\u8ba4\u7684\u6b63\u5e38\u90ae\u4ef6</li>
           <li>CONFIRMED_HAM_MAILFOLDER_CS_CZ=Potvrzen\u00e1 norm\u00e1ln\u00ed po\u0161ta</li>
           <li>CONFIRMED_HAM_MAILFOLDER_HU_HU=Elfogadott \u00e1l-k\u00e9retlen</li>
           <li>CONFIRMED_HAM_MAILFOLDER_SK_SK=Potvrden\u00e9 ako nie spam</li>
           <li>CONFIRMED_HAM_MAILFOLDER_LV_LV=Apstiprin\u0101ts "ham"</li>
          <ul>
      defaultValue:
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: AdminUser.properties
      packageName: open-xchange-admin
      tags: ["Admin", "User", "Mail", "Folder"]