feature_name: Advertisement
feature_description: |
  This page describes the properties related to the advertisement feature.

  See [[https://documentation.open-xchange.com/{{version}}/middleware/components/Advertisement.html]] for more informations.
properties:
  - key: com.openexchange.advertisement.[reseller].packageScheme
    description: |
      Defines which package scheme is used for the reseller. [reseller] can be replaced with either the reseller name or the reseller id.
      Use 'OX_ALL' for the default reseller. Available package schemes are:
      <ul>
       <li>Global - always uses the default reseller and default package.</li>
       <li>AccessCombinations - Using access combination names to retrieve the package.</li>
       <li>TaxonomyTypes - Using taxonomy types to retrieve the package.</li>
      </ul>
    defaultValue: Global
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: advertisement.properties
    packageName: open-xchange-advertisement
    tags: ["Reseller"]
  - key: com.openexchange.advertisement.[reseller].taxonomy.types
    description: |
      Defines a comma separated list of taxonomy types which are used as package identifiers. 
      This list is used by the 'TaxonomyTypes' package scheme to identify the package.
    defaultValue: 
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: com.openexchange.advertisement.[reseller].packageScheme
    file: advertisement.properties
    packageName: open-xchange-advertisement
    tags: ["Reseller"]