feature_name: Drive Client Windows
properties:
    - key: com.openexchange.drive.updater.path
      description: |
        The path of the "files"-directory where branded updater's and the branding property file's will be placed.
        The file's must be placed within an own folder per branding.
        For example the folder tree could look like this:  
        <pre>
        [path]  
            -generic  
                -generic.branding  
                -OX Drive_vX.Y.Z.exe  
                -OX Drive_vX.Y.Z.msi  
            -yourOwnBranding  
                -[...]  
        </pre>
      defaultValue: /opt/open-xchange/files/drive-client/windows
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: drive-client-windows.properties
      packageName: open-xchange-drive-client-windows
      tags: ["Drive Client Windows"]
    - key: com.openexchange.drive.updater.tmpl
      description: |
        The filename of the drive updater template.
      defaultValue: oxdrive_update.tmpl
      version: 
      reloadable: true
      configcascadeAware: false
      related: 
      file: drive-client-windows.properties
      packageName: open-xchange-drive-client-windows
      tags: ["Drive Client Windows"]     
    - key: com.openexchange.drive.update.branding
      description: |
        The name of the system wide drive branding identifier.
        This name must be equal to the name of one of the subfolder's under [[com.openexchange.drive.updater.path]].
      defaultValue: generic
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: drive-client-windows.properties
      packageName: open-xchange-drive-client-windows
      tags: ["Drive Client Windows"]  
    - key: com.openexchange.drive.windows.binaryRegex.exe
      description: |
        The regex to match the exe artifacts of the drive clients build job.
      defaultValue: .*_v([0-9.]+).exe
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: drive-client-windows.properties
      packageName: open-xchange-drive-client-windows
      tags: ["Drive Client Windows"]  
    - key: com.openexchange.drive.windows.binaryRegex.msi
      description: |
        The regex to match the msi artifacts of the drive clients build job.
      defaultValue: .*_v([0-9.]+).msi
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: drive-client-windows.properties
      packageName: open-xchange-drive-client-windows
      tags: ["Drive Client Windows"]  