feature_name: Filestore S3
feature_description: |
  This file provides the configuration of all file storages based on the
  Amazon Simple Storage Service (Amazon S3). Each connected storage is
  identified by a so called "filestore ID", which refers to the authority
  part of the URI configured in the "uri" column in the "filestore" table of
  the config database, previously registered using  
  <pre>./registerfilestore -t [filestoreID]</pre>
  For each configured filestore, an own set of the properties may be defined,
  replacing [filestoreID] with the actual identifier.

  See [[https://documentation.open-xchange.com/{{version}}/middleware/components/filestore.html]] for more informations
  about filestores.
properties:
    - key: com.openexchange.filestore.s3.[filestoreID].endpoint
      description: |
        Specifies the endpoint (e.g. "ec2.amazonaws.com") or a full URL, including
        the protocol (e.g. "https://ec2.amazonaws.com") of the region specific AWS
        endpoint this client will communicate with.
      defaultValue: s3.amazonaws.com
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].bucketName
      description: |
        Specifies the name of the parent bucket to use. The bucket will be created
        automatically if it not yet exists, however, it's still possible to use an
        already existing one. There are some naming restrictions, please refer to
        [[http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html]] for
        details. This property is required.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].region
      description: |
        Configures the Amazon S3 region to use when creating new buckets. This value
        is also used to pre-configure the client when no specific endpoint is set.  
        Possible values:
        <ul>
          <li><code>us-gov-west-1</code></li>
          <li><code>us-east-1</code></li>
          <li><code>us-west-1</code></li> 
          <li><code>us-west-2</code></li>
          <li><code>eu-west-1</code></li>
          <li><code>ap-southeast-1</code></li>
          <li><code>ap-southeast-2</code></li>
          <li><code>ap-northeast-1</code></li>
          <li><code>sa-east-1</code></li>
        </ul>
      defaultValue: us-west-2
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].pathStyleAccess
      description: |
        Defines if path-style-access should be used when accessing the S3 API. If
        not set to <code>true</code>, virtual-hosted-style access is used. Please refer to
        [[http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html]] for
        details.
      defaultValue: true
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].accessKey
      description: |
        Configures the AWS access key to use. This property is required.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].secretKey
      description: |
        Configures the AWS secret key to use. This property is required.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].encryption
      description: |
        Optionally specifies which client-side encryption should be used. Current
        options include <code>none</code> for no encryption, or <code>rsa</code> for an RSA-based asymmetric
        encryption.  
        Please note that depending on the used key length and Java runtime, one
        might need to replace the so-called "JCE Unlimited Strength Jurisdiction
        Policy Files" accordingly.
      defaultValue: none
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].encryption.rsa.keyStore
      description: |
        Specifies the path to the local keystore file (PKCS #12) containing the
        public-/private-key pair to use for encryption, e.g.
        "/opt/open-xchange/etc/cert/awss3.p12". Required if
        [[com.openexchange.filestore.s3.[filestoreID].encryption]] is set to <code>rsa</code>.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.filestore.s3.[filestoreID].encryption
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]

    - key: com.openexchange.filestore.s3.[filestoreID].encryption.rsa.password
      description: |
        Specifies the password used when creating the referenced keystore containing
        public-/private-key pair to use for encryption. Note that blank or null
        passwords are in violation of the PKCS #12 specifications. Required if
        [[com.openexchange.filestore.s3.[filestoreID].encryption]] is set to <code>rsa</code>.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.filestore.s3.[filestoreID].encryption
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore", "Credential"]

    - key: com.openexchange.filestore.s3.[filestoreID].signerOverride
      description: |
        Optionally configures an override for the algorithm used to sign requests
        against the S3 interface. If left empty, the underlying client will choose a
        suitable signer type based on the actually used service and region
        automatically, however, auto-detection only works properly for the "vanilla"
        Amazon S3, and may lead to unwanted results when targeting an S3
        implementation where not all signature types are supported.
        Possible values include <code>S3SignerType</code> to enforce the AWS signature v2, and
        <code>AWSS3V4SignerType</code> for AWS signature v4.
        For backwards compatibility, the setting defaults to <code>S3SignerType</code>, and
        needs to be adjusted explicitly when targeting the newer "v4-only" regions
        like Frankfurt or Beijing.
      defaultValue: S3SignerType
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-s3.properties
      packageName: open-xchange-filestore-s3
      tags: ["Filestore"]