feature_name: Filestore sproxyd
feature_description: |
  This properties configure file storages based on the
  Scality sproxyd API. Each connected storage is identified by a so called 
  "filestore ID", which refers to the authority part of the URI configured 
  in the "uri" column in the "filestore" table of the config database, 
  previously registered using:
  <pre>./registerfilestore -t [filestoreID]</pre>
  For each configured filestore, an own set of the properties may be defined, 
  replacing [filestoreID] with the actual identifier.

  See [[https://documentation.open-xchange.com/{{version}}/middleware/components/filestore.html]] for more informations
  about filestores.
properties:
    - key: com.openexchange.filestore.sproxyd.[filestoreID].protocol
      description: |
        Specifies the protocol to be used for network communication (http or https)
        This property is required.
      defaultValue: 
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore"]

    - key: com.openexchange.filestore.sproxyd.[filestoreID].hosts
      description: |
        Specifies the hosts as &lt;hostname&gt;:&lt;port&gt; pairs to be used for network communication.
        At least one host must be provided, multiple hosts can be specified as comma-separated
        list.
        This property is required.
      defaultValue:
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Host", "Port"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].path
      description: |
        The path under which sproxyd is available. The path must lead to the namespace under
        which OX related files shall be stored. It is expected that the namespace configuration
        is available under &lt;protocol&gt;://&lt;host&gt;/&lt;path&gt;/.conf.
        This property is required.
      defaultValue:
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Host"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].maxConnections
      description: |
        The max. number of concurrent HTTP connections that may be established with the sproxyd
        endpoints. If you have specified more than one hosts, this setting should be configured
        so that  
        maxConnectionsPerHost < maxConnections <= n * maxConnectionsPerHost.
      defaultValue: 100
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Limit"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].maxConnectionsPerHost
      description: |
        The max. number of concurrent HTTP connections that may be established with a certain
        sproxyd endpoint.
      defaultValue: 100
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Limit"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].connectionTimeout
      description: |
        The connection timeout in milliseconds. If establishing a new HTTP connection to a certain
        host, it is blacklisted until it is considered available again. A periodic heartbeat task
        that tries to read the namespace configuration (&lt;protocol&gt;://&lt;host&gt;/&lt;path&gt;/.conf) decides
        whether an endpoint is considered available again.
      defaultValue: 5000
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Black List", "Timeout"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].socketReadTimeout
      description: |
        The socket read timeout in milliseconds. If waiting for the next expected TCP packet exceeds
        this value, the host is blacklisted until it is considered available again. A periodic heartbeat
        task that tries to read the namespace configuration (&lt;protocol&gt;://&lt;host&gt;/&lt;path&gt;/.conf) decides
        whether an endpoint is considered available again.
      defaultValue: 15000
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Black List", "Timeout"]
      
    - key: com.openexchange.filestore.sproxyd.[filestoreID].heartbeatInterval
      description: |
        Hosts can get blacklisted if the client consieders them to be unavailable. All hosts on the
        blacklist are checked periodically if they are available again and are then removed from the
        blacklist if so. A host is considered available again if the namespace configuration file
        (&lt;protocol&gt;://&lt;host&gt;/&lt;path&gt;/.conf) can be requested without any error.
        This setting specifies the interval in milliseconds between two heartbeat runs. The above
        specified timeouts must be taken into account for specifying a decent value, as every heartbeat
        run might block until a timeout happens for every still unavailable host.
      defaultValue: 60000
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: filestore-sproxyd.properties
      packageName: open-xchange-filestore-sproxyd
      tags: ["Filestore", "Black List"]
