feature_name: Find
properties:
    - key: com.openexchange.find.basic.mail.allMessagesFolder
      description: |
        Some mail backends provide a virtual folder that contains all messages of
        a user to enable cross-folder mail search. Open-Xchange can make use of
        this feature to improve the search experience.
        Set the value to the name of the virtual mail folder containing all messages.
        Leave blank if no such folder exists.
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: findbasic.properties
      packageName: open-xchange-core
      tags: ["Find", "Mail"]
    - key: com.openexchange.find.basic.mail.searchmailbody
      description: |
        Denotes if mail search queries should be matched against mail bodies.
        This improves the search experience within the mail module, if your mail
        backend supports fast full text search. Otherwise it can slow down the
        search requests significantly.
        Change the value to <code>true</code>, if fast full text search is supported.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related:
      file: findbasic.properties
      packageName: open-xchange-core
      tags: ["Find", "Mail"]