feature_name: Folder JSON
properties:
    - key: com.openexchange.folder.json.module
      description: |
        Define the module which also serves as the appendix for registered servlet:
        If module is set to <code>myfolders</code>, the servlet path is changed to "/ajax/myfolders".
      defaultValue: folders
      version:
      reloadable: false
      configcascadeAware: false
      related:
      file: folderjson.properties
      packageName: open-xchange-core
      tags: ["Folder", "JSON"]
    - key: com.openexchange.folder.json.servletPath
      description: |
        Define the path for registered servlet.
        If set, the complete path is set to specified value regardless of the value of [[com.openexchange.folder.json.module]] property.
        If left empty the path is: "/ajax/" + &lt;module&gt;
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related:
      file: folderjson.properties
      packageName: open-xchange-core
      tags: ["Folder", "JSON"]