feature_name: Folder
properties:
    - key: com.openexchange.folderstorage.defaultPermissions
      description: |
        Specifies default permission to use in case folder is supposed to be created below a certain parent folder.
        The value is a pipe (<code>|</code>) separated listing of expressions; each expression defines the default permissions
        for a denoted parent folder. Currently the reserved folder identifiers "2" and "15" are considered as "2"
        denoted the public PIM folder whereas "15" denotes the public Drive folder.

        An expression starts with the parent folder identifier followed by <code>=</code> character; e.g. "2=".  
        Then there is a comma-separated list of permissions to assume per entity (user or group).

        Each permission either starts with <code>user_</code>, <code>admin_user_</code>, <code>group_</code> or <code>admin_group_</code> (the prefix "admin_" controls
        whether the entity is supposed to be set as folder administrator) followed by the numeric entity identifier.

        Then an <code>@</code> character is supposed to occur and finally followed by a rights expression. The rights may be dot-separated  
        listing (<code>&lt;folder-permission&gt;.&lt;read-permission&gt;.&lt;write-permission&gt;.&lt;delete-permission&gt;</code>) or one
        of the tokens  <code>viewer</code>, <code>writer</code> or <code>author</code>.

        More formally:
        <pre>
        expressions = expression ("|" expression)*
        expression = folder "=" permission ("," permission)*
        permission = ("admin_")? ("group_" | "user_") entity(int) "@" rights
        rights = (folder-permission(int) "." read-permission(int) "." write-permission(int) "." delete-permission(int)) | ("viewer" | "writer" | "author")
        </pre>
        Example 1:
        <pre>
        com.openexchange.folderstorage.defaultPermissions=2=group_2@2.4.0.0,admin_user_5@8.4.4.4|15=admin_group_2@8.8.8.8
        </pre>
        Example 2:
        <pre>
        com.openexchange.folderstorage.defaultPermissions=2=group_2@viewer,admin_user_5@author|15=admin_group_2@writer  
        </pre>
      defaultValue: No defaut value
      version: 7.8.4
      reloadable: true
      configcascadeAware: true
      related: 
      file: folder.properties
      packageName: open-xchange-core
      tags: ["Folder","Permission"]
    - key: com.openexchange.folderstorage.inheritParentPermissions
      description: |
        Specifies if permissions of new parent folder should be applied when moving a folder into the public folder tree.
      defaultValue: false
      version: 7.8.4
      reloadable: false
      configcascadeAware: false
      related: 
      file: folder.properties
      packageName: open-xchange-core
      tags: ["Folder","Permission"]
    - key: com.openexchange.folderstorage.inheritParentPermissions
      description: |
        Specifies if permissions of new parent folder should be applied when moving a folder into the public folder tree.
      defaultValue: false
      version: 7.8.4
      reloadable: false
      configcascadeAware: false
      related: 
      file: folder.properties
      packageName: open-xchange-core
      tags: ["Folder","Permission"]
    - key: ENABLE_DB_GROUPING
      description: |
        Define where to perform folder grouping.
        This filters the database results for duplicate folders in the where 
        clause of the db statement or afterwards in the application. 
        Possible values: <code>TRUE</code> / <code>FALSE</code>.
      defaultValue: TRUE
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder","Caching"]
    - key: ENABLE_FOLDER_CACHE
      description: |
        Enable or disable folder caching. Possible values: <code>TRUE</code> / <code>FALSE</code>.
      defaultValue: TRUE
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder","Caching"]
    - key: IGNORE_SHARED_ADDRESSBOOK
      description: |
        Determine whether to ignore 'shared addressbook' folder or not.
        Possible values: <code>TRUE</code> / <code>FALSE</code>.
      defaultValue: TRUE
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder","Caching", "Contact"]
    - key: ENABLE_INTERNAL_USER_EDIT
      description: |
        Define if users are allowed to edit their own contact object
        contained in folder 'Global Address Book' aka 'Internal Users'.
      defaultValue: TRUE
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder", "Contact"]
    - key: com.openexchange.folderstorage.outlook.showPersonalBelowInfoStore
      description: |
          Specifies whether a user's default InfoStore folder should appear below
          InfoStore root folder:
          <pre>
          - Infostore
          -- My files
          -- Public infostore
          -- Userstore
          -- Other infstore folders
          </pre>
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder"]
    - key: com.openexchange.folderstorage.database.preferDisplayName
      description: |
        Specifies whether default InfoStore folders are labeled with owning user's display name
        or name is read from folder storage (database).
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: false
      related: 
      file: foldercache.properties
      packageName: open-xchange-core
      tags: ["Folder", "Database"]
