feature_name: LinkedIn
properties:
    - key: com.openexchange.halo.linkedin.enabledMailCapableKey
      description: |
        Specify whether LinkedIn API key/secret are allowed to access E-Mail-sensitive data.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: halo-linkedin.properties
      packageName: open-xchange-linkedin
      tags: ["Halo", "LinkedIn"]