feature_name: IMAP Auth
properties:
    - key: IMAP_SERVER
      description: |
        IMAP server ip or fqdn.
      defaultValue: localhost
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication","IMAP", "Host"]
    - key: IMAP_PORT
      description: |
        Port on which the IMAP server is listening.
      defaultValue: 143
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication","IMAP", "Port"]
    - key: IMAP_USE_SECURE
      description: |
        Set to <code>true</code> if connecting via "imaps://".
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication","IMAP", "Security"]
    - key: IMAP_TIMEOUT
      description: |
        Socket I/O timeout value in milliseconds.
      defaultValue: 5000
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication","IMAP", "Timeout"]
    - key: IMAP_CONNECTIONTIMEOUT
      description: |
        Socket connection timeout value in milliseconds.
      defaultValue: 5000
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication","IMAP", "Timeout"]
    - key: USE_FULL_LOGIN_INFO
      description: |
        Set to <code>true</code> to auth with "user@domain" instead of just "user" against imap server.
        If <code>true</code> the "domain" part will be used as the context name of the ox system.
        so add "domain" as a login mapping to be able to login.
        If false, the plugin react as only one context exists in the ox system,
        and this context has the mapping "defaultcontext" added.
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]
    - key: USE_FULL_LOGIN_INFO_FOR_USER_LOOKUP
      description: |
        Define if the internal user-name matches the full login string or just the user part;
        meaning the user is supposed to be queried using "user@domain" instead of "user".
        
        Note:  
        This property is only effective if [[USE_MULTIPLE]] is set to <code>true</code>.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: USE_MULTIPLE
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]
    - key: USE_FULL_LOGIN_INFO_FOR_CONTEXT_LOOKUP
      description: |
        Define if the internal context-name matches the full login string or just the domain part;
        meaning the context is supposed to be queried using "user@domain" instead of "domain".
        
        Note:  
        This property is only effective if [[USE_MULTIPLE]] is set to <code>true</code>.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: USE_MULTIPLE
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]
    - key: LOWERCASE_FOR_CONTEXT_USER_LOOKUP
      description: |
        Specifies whether user/context look-up is supposed to be performed
        by lower-casing the utilized user/context information.
        
        Note:  
        This property is only effective if [[USE_MULTIPLE]] is set to <code>true</code>.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: USE_MULTIPLE
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]
    - key: USE_MULTIPLE
      description: |
        If set to true the IMAP authentication plugin gets all IMAP server information from the OX database instead of reading
        configuration from this file.
        Following information is fetched from DB and will be used to authenticate against the server:
        <ul>
         <li>server</li>
         <li>port</li>
         <li>ssl/tls</li>
        </ul>
        Moreover the proper login name is detected as configured by property [[com.openexchange.mail.loginSource]].
        To use this feature, set the correct values while provisioning an OX user.
        Useful if you have many IMAP Servers to connect to.
        
        INFO: Domain part of the login is used as context name.
        
        Example:  
        test@test.org  
        Username of the OX account must be "test" and name of the OX context must be "test.org".
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: ["LOWERCASE_FOR_CONTEXT_USER_LOOKUP", "USE_FULL_LOGIN_INFO_FOR_CONTEXT_LOOKUP", "USE_FULL_LOGIN_INFO_FOR_USER_LOOKUP", "com.openexchange.mail.loginSource"]
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]
    - key: com.openexchange.authentication.imap.imapAuthEnc
      description: |
        Define the encoding for IMAP authentication.
      defaultValue: UTF-8
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: imapauth.properties
      packageName: open-xchange-authentication-imap
      tags: ["IMAP Auth","Authentication", "IMAP"]