feature_name: Jump
properties:
    - key: com.openexchange.jump.endpoint.[system-name]
      description: |
        Specifies a list jump end-points.
        [system-name] must be replaced with the name of the system. 
        E.g. <pre>com.openexchange.jump.endpoint.mysystem=http://my.host.invalid/identities?action=receiveIdentity</pre>
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: tokens.properties
      packageName: open-xchange-core
      tags: ["Jump", "Host"]