feature_name: LDAP
properties:
    - key: java.naming.provider.url
      description: |
        URL of the LDAP server to connect to for authenticating users.
        "ldaps" is supported.
      defaultValue: ldap://localhost:389/dc=example,dc=com
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: java.naming.security.authentication
      description: |
        Defines the authentication security that should be used.
      defaultValue: simple
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: com.sun.jndi.ldap.connect.timeout
      description: |
        Timeouts are useful to get quick responses for login requests. 
        This timeout is used if a new connection is established.
      defaultValue: 10000
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication", "Timeout"]
    - key: com.sun.jndi.ldap.read.timeout
      description: |
        This timeout only works since Java 6 SE to time out waiting for a response.
      defaultValue: 10000
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication", "Timeout"]
    - key: useFullLoginInfo
      description: |
        Set to <code>true</code> to authenticate with the string entered in the login name field, e.g.
        "user@domain" instead of just "user" against ldap server.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: uidAttribute
      description: |
        This attribute is used for login. E.g. uid=<login>,baseDN

        Note:  
        If the attribute is not part of the user dn, you need to set [[bindOnly]] to <code>false</code>.
      defaultValue: uid
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: baseDN
      description: |
        This is the base distinguished name where the user are located.
      defaultValue: ou=Users,ou=OxObjects,dc=open-xchange,dc=com
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: ldapReturnField
      description: |
        If you do not want to pass on the user id, used for authentication, to the
        groupware but another field entry of the LDAP user object, then you can
        specify the field here.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: adsBind
      description: |
        This option activates a special ADS bind. It allows the user to
        authenticate at the ADS with only the displayName or by using the syntax:
        <pre>
        DOMAIN\Samaccountname
        </pre>
        Note that "\" cannot be used in user names when this option is activated.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: bindOnly
      description: |
        Set this to <code>false</code> if the user entries are not directly contained in the
        entry of the dn, and you have to search within ldap, change ldapScope
        in order to define the search depth.

        Note:  
        When two users exist with the same uidAttribute, authentication
        will be refused, though.
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: ldapScope
      description: |
        Set the ldap search scope in case [[bindOnly]] is set to <code>false</code>.
        Possible values:
        <ul>
          <li><code>subtree</code></li>
          <li><code>onelevel</code></li>
          <li><code>base</code></li>
        </ul>
      defaultValue: subtree
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: searchFilter
      description: |
        Specify the filter to limit the search of user entries (used in combination with subtreeSearch=true).
        The filter will be ANDed with the attributed specified in uidAttribute.

        Example:
        <code>(&(objectclass=posixAccount)(uid=foo))</code>
      defaultValue: (objectclass=posixAccount)
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: bindDN
      description: |
        If your LDAP server does not allow to do searches without any authentication,
        specify a dn here to bind in order to search (used in combination with subtreeSearch=true).
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: bindDNPassword
      description: |
        The password required for the bindDN.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication", "Credential"]
    - key: referral
      description: |
        This option configures how to handle the chasing of referrals in LDAP 
        (see [[http://java.sun.com/products/jndi/tutorial/ldap/referral/overview.html]]).  
        Possible values:
        <ul>
          <li><code>ignore</code></li>
          <li><code>follow</code></li>
          <li><code>throw</code></li>
        </ul>
      defaultValue: follow
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]
    - key: proxyUser
      description: |
        Comma separated list of login names allowed to login as a proxy for every other user.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication", "Credential"]
    - key: proxyDelimiter
      description: |
        Define a delimiter to be used to seperate Proxy from Userlogin.
        If defined, a proxy user can login on behalf of a user using the form:  
        <pre>
        &lt;PROXYACCOUNT&gt;&lt;DELIMITER&gt;&lt;USERACCOUNT&gt;
        </pre>
        Note:
          <ol>
            <li>The underlying Mailserver must support SASL AUTHPROXYING.  
                The open-xchange mailfilterbundle does not support it, so it will
                raise errors.</li>
            <li>The same option has to be set in mail.properties</li>
          </ol>
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: ldapauth.properties
      packageName: open-xchange-authentication-ldap
      tags: ["LDAP", "Authentication"]