feature_name: Mail Filter
properties:
    - key: com.openexchange.mail.filter.loginType
      description: |
        Specifies which sieve server should be used. Two options are allowed here:
        <ul>
          <li><code>user</code> - use the imap server setting stored for user in the database</li>
          <li><code>global</code> - use the sieve server given in [[com.openexchange.mail.filter.server]] for all users.</li>
        </ul>
      defaultValue: user
      version:
      reloadable: true
      configcascadeAware: true
      related: com.openexchange.mail.filter.server
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.credentialSource
      description: |
        Specifies which sieve credentials should be use. Four options are allowed here:
        <ul>
          <li><code>session</code> - login name and password are used from the current session.</li>
          <li><code>session-full-login</code> - full login (incl. context part) name and password are used from the current session.</li>
          <li><code>imapLogin</code> - the login name is taken from the field imapLogin of the current user, the password is taken from the current session.</li>
          <li><code>mail</code> - use the primary mail address of the user and the password from the session.</li>
        </ul>
      defaultValue: session
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.server
      description: |
        Specifies a default value for the sieve server.
      defaultValue: localhost
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Host", "Sieve"]
    - key: com.openexchange.mail.filter.port
      description: |
        Specifies the Sieve port.

        Note:  
        <code>2000</code> is the deprecated port number for Sieve (now assigned to some Cisco SCCP protocol by the IANA).  
        <code>4190</code> is the new one used with most recent Linux and IMAP implementations.  
        Please check your system's default port defined at /etc/services.  
      defaultValue: 4190
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Port", "Sieve"]
    - key: com.openexchange.mail.filter.scriptName
      description: |
        Specifies the name of the script, which will be generated.
        Note that the mail filter bundle will leave the old script with the old
        script name behind, and doesn't delete it.
      defaultValue: Open-Xchange
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.authenticationEncoding
      description: |
        Define the charset encoding to use for authentication to sieve server.
      defaultValue: UTF-8
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.nonRFCCompliantTLSRegex
      description: |
        Define the regex which recognizes servers with incorrect sieve TLS implementation.
      defaultValue: "^Cyrus.*v([0-1]\\.[0-9].*|2\\.[0-2].*|2\\.3\\.[0-9]|2\\.3\\.[0-9][^0-9].*)$"
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.tls
      description: |
        Whether to use TLS if available.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Security"]
    - key: com.openexchange.mail.filter.vacationDomains
      description: |
        Specifies if a vacation messages should only be sent to specific domains.
        If multiple domains are given, they should be separated by ",".  
        E.g.: 
        <pre>com.openexchange.mail.filter.vacationDomains=testdomain.com,example.com</pre>
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.connectionTimeout
      description: |
        Specifies when the connection should time out (value in milliseconds).
      defaultValue: 30000
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Timeout"]
    - key: com.openexchange.mail.filter.authTimeout
      description: |
        Specifies when the connection should time out (value in milliseconds) when performing SASL authentication against Sieve end-point.
      defaultValue: 6000
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Timeout"]
    - key: com.openexchange.mail.filter.passwordSource
      description: |
        Set the password source; meaning which source is taken to determine a user's password to login into mail filter system.  
        If <code>session</code> is set, then user's individual system's password is taken.  
        If <code>global</code> is set, then the value specified through property 'com.openexchange.mail.filter.masterPassword' is taken.  
        Currently known values: <code>session</code> and <code>global</code>
      defaultValue: session
      version:
      reloadable: true
      configcascadeAware: true
      related: com.openexchange.mail.filter.masterPassword
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.masterPassword
      description: |
        The master password for mail/transport server. Only takes effect when property
        [[com.openexchange.mail.filter.passwordSource]] is set to <code>global</code>.
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: true
      related: com.openexchange.mail.filter.passwordSource
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Credential"]
    - key: com.openexchange.mail.filter.useUTF7FolderEncoding
      description: |
        This property defines if mailbox names shall be UTF-7 encoded as specified in RFC2060; section 5.1.3. "Mailbox International Naming Convention".
        If set to <code>false</code> no UTF-7 encoding is performed.

        Set to <code>true</code> for those Cyrus IMAP server versions that do NOT support "sieve_utf8fileinto" property (e.g. lower than v2.3.11).  
        Set also to <code>true</code> for those Cyrus IMAP server versions that support "sieve_utf8fileinto" property and having that property set to "0".  
        Thus moving mails with the 'fileinto' command will properly work for mailbox names that contain non-ascii characters.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.punycode
      description: |
        Enable punycode encoding for the username used in authentication against the managesieve server.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.useSieveResponseCodes
      description: |
        Interpret Sieve Response Codes, see [[https://tools.ietf.org/html/rfc5804#section-1.3]].
        In most cases, this option must be kept to <code>false</code>.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]
    - key: com.openexchange.mail.filter.redirectWhitelist
      description: |
        Specifies a comma-separated list of domains (wild-card syntax supported) that are allowed for redirect rules.
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "White List"]
    - key: com.openexchange.mail.filter.preferredSaslMech
      description: |
        Specifies the preferred SASL authentication mechanism.
        An empty value falls-back to "PLAIN".
        
        Known values: <code>GSSAPI</code>, <code>XOAUTH2</code>, <code>OAUTHBEARER</code>
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
    - key: com.openexchange.mail.filter.options.allowNestedTests
      description: |
        A flag announced to clients via the config action to indicate if they should allow nested tests.

        Note:  
        This flag is only announced via the new v2 mailfilter api.
      defaultValue: true
      version: 7.8.4
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve"]    
    - key: com.openexchange.mail.filter.blacklist.[base]
      description: |
        Defines a comma separated list of elements. Each elements is either a test name, an action name or a comparison depending on the [base].  
        [base] must be one of:
        <ul>
        	<li>tests</li>
        	<li>actions</li>
        	<li>comparisons</li>
        </ul>
        e.g.:
        <pre>
        com.openexchange.mail.filter.blacklist.actions = keep, discard
        </pre>
        	
        This will blacklist the actions 'keep' and 'discard' and will not show it to clients.

        Note:  
        1. Invalid elements will be ignored.  
        2. This blacklist is only applicable for the new v2 mailfilter api.
      defaultValue: 
      version: 7.8.4
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Black List"]
    - key: com.openexchange.mail.filter.blacklist.[base].[element].[field]
      description: |
        Defines a comma separated list of strings. Each string represents a value which should be blacklisted from the corresponding field of the element.
          
        [base] must be one of:
        <ul>
        	<li>tests</li>
        	<li>actions</li>
        </ul>
        Currently only <code>tests</code> contains sub fields.

        [element] must be a valid element of the base group. E.g. <code>address</code> for <code>tests</code> or <code>keep</code> for <code>actions</code>.

        [field] must be a valid field of the element. E.g. <code>comparisons</code>

        e.g.:
        <pre>
        com.openexchange.mail.filter.blacklist.tests.from.comparisons = is
        </pre>
        This will blacklist the <code>is</code> comparator from the <code>from</code> action.

        Note:  
        This blacklist is only applicable for the new v2 mailfilter api.
      defaultValue: 
      version: 7.8.4
      reloadable: true
      configcascadeAware: true
      related:
      file: mailfilter.properties
      packageName: open-xchange-mailfilter
      tags: ["Mail Filter", "Mail", "Sieve", "Black List"]