feature_name: Participant
feature_description: |
  The participant properties must be defined in a file named "participant.properties". Otherwise the properties will not be applied.
properties:
    - key: com.openexchange.participant.ShowWithoutEmail
      description: |
        When searching for external participants in contact folders this option
        defines if contacts without email address are shown.
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: participant.properties
      packageName: open-xchange-core
      tags: ["Participant", "Mail"]
properties:
    - key: com.openexchange.participant.autoSearch
      description: |
        When searching for participants and the participants selection dialog is
        opened this option defines if initially all users, groups and resources are
        displayed or not. If this option is <code>true</code> every opening of the dialog triggers
        a search request on the server.
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: participant.properties
      packageName: open-xchange-core
      tags: ["Participant", "Search"]