feature_name: Password Change Script
feature_description: |
  The package open-xchange-passwordchange-script allows you to run a command to
  change a password in an external subsystem like e.g. LDAP.
properties:
    - key: com.openexchange.passwordchange.script.shellscript
      description: |
        Script which updates the user's password. Must be executable (+x) and
        have correct interpreter set e.g. #!/bin/bash

        The following values are passed by the servlet to the script:  
        1. --cid - Context ID  
        2. --username - Username of the logged in user  
        3. --userid - User ID of the logged in user  
        4. --oldpassword - Old user password  
        5. --newpassword - New user password

        See [[http://oxpedia.org/wiki/index.php?title=ChangePasswordExternal]]
        for some examples.

        If script does not exit with status code 0, an io-error is shown in
        the GUI.

        The following exit codes will display a defined error:  
        1: Cannot change password < %s >, see logfiles for details.  
        2: New password is too short  
        3: New password is too weak  
        4: Cannot find user  
        5: LDAP error
      defaultValue: 
      version:
      reloadable: true
      configcascadeAware: false
      related: com.openexchange.passwordchange.script.base64
      file: change_pwd_script.properties
      packageName: open-xchange-passwordchange-script
      tags: ["Password Change Script"]
    - key: com.openexchange.passwordchange.script.base64
      description: |
        Indicates if the string based script parameters like username,
        oldpassword and newpassword should be encoded as Base64 to circumvent
        character encoding issues on improperly configured distributions not
        providing an unicode environment for the process.
      defaultValue: false
      version: 7.8.4
      reloadable: true
      configcascadeAware: false
      related: com.openexchange.passwordchange.script.shellscript
      file: change_pwd_script.properties
      packageName: open-xchange-passwordchange-script
      tags: ["Password Change Script"]
