feature_name: PasswordChangeHistory
feature_description: |
  This page describes the available properties for password change history.
  
  
properties:
    - key: com.openexchange.passwordchange.history.enabled
      description: |
        Whether to start the recording of password changes or not.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: true
      related: 
      file: 
      packageName: open-xchange-core
      tags: ["Password Change History", "History"]
    - key: com.openexchange.passwordchange.history.limit
      description: |
        The number of entries that the server should keep. If set to "0" all entries for given user will be deleted.
      defaultValue: 10
      version:
      reloadable: false
      configcascadeAware: true
      related: 
      file: 
      packageName: open-xchange-core
      tags: ["Password Change History", "History"]
    - key: com.openexchange.passwordchange.history.recorder
      description: |
        The actual recorder that saves and retrieves the data. Currently shipped "default" for a MySQL implementation.
      defaultValue: "default"
      version:
      reloadable: false
      configcascadeAware: true
      related: 
      file: 
      packageName: open-xchange-core
      tags: ["Password Change History", "History"]
    