feature_name: Report client
feature_description: |
  The first part defines if a proxy server should be used to establish the http connection
  to the Open-Xchange report server, and if which server and proxy details to use.
  The second part configures report serialization.

  See [[https://documentation.open-xchange.com/{{version}}/middleware/components/report_client.html]] for more informations.
properties:
    - key: com.openexchange.report.client.proxy.useproxy
      description: |
        Determine wether a proxy should be used or not. If set to <code>true</code>, the related properties also have to be set.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: ["com.openexchange.report.client.proxy.address", "com.openexchange.report.client.proxy.port", "com.openexchange.report.client.proxy.authrequired"]
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy"]
    - key: com.openexchange.report.client.proxy.address
      description: |
        The address of the proxy, that should be used.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.report.client.proxy.port
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy"]
    - key: com.openexchange.report.client.proxy.port
      description: |
        The port of the proxy, that should be used.
      defaultValue: 8080
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.report.client.proxy.address
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy", "Port"]
    - key: com.openexchange.report.client.proxy.authrequired
      description: |
        Is authorisation required to use the proxy. If set to <code>true</code>, the related properties have alsos to be set.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related: ["com.openexchange.report.client.proxy.username", "com.openexchange.report.client.proxy.password"]
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy"]
    - key: com.openexchange.report.client.proxy.username
      description: |
        The username that should be used to autherise on the proxy server.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.report.client.proxy.password
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy", "Credential"]
    - key: com.openexchange.report.client.proxy.password
      description: |
        The password that should be used to autherise on the proxy server.
      defaultValue:
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.report.client.proxy.username
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Proxy", "Credential"]
    - key: com.openexchange.report.appsuite.fileStorage
      description: |
        Where should parts of the report be stored.
      defaultValue: /tmp
      version: 7.8.3
      reloadable: true
      configcascadeAware: false
      related:
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Serialization"]
    - key: com.openexchange.report.appsuite.maxChunkSize
      description: |
        How many capability-Sets should be hold in memory before writing them into a file.
      defaultValue: 200
      version: 7.8.3
      reloadable: true
      configcascadeAware: false
      related:
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Serialization"]
    - key: com.openexchange.report.appsuite.maxThreadPoolSize
      description: |
        How many threads can be used for report processing.
      defaultValue: 20
      version: 7.8.3
      reloadable: true
      configcascadeAware: false
      related:
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Serialization", "Thread"]
    - key: com.openexchange.report.appsuite.threadPriority
      description: |
        Which thread priority do the processing threads have.
      defaultValue: 1
      version: 7.8.3
      reloadable: true
      configcascadeAware: false
      related:
      file: reportclient.properties
      packageName: open-xchange-report-client
      tags: ["Report", "Serialization", "Thread"]