feature_name: Report
properties:
  - key: com.openexchange.report.appsuite.fileStorage
    description: |
      Reports filestorage directory for storage of report parts and composed data.
    defaultValue: /tmp
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    packageName: open-xchange-core
    tags: ["Report"]
  - key: com.openexchange.report.appsuite.maxChunkSize
    description: |
      Determines how many chunks of data can be kept in the report before saving them in the folder described in 
      [[com.openexchange.report.client.fileStorage]].
    defaultValue: 200
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    packageName: open-xchange-core
    tags: ["Report","Limit"]
  - key: com.openexchange.report.appsuite.maxThreadPoolSize
    description: |
      Number of threads allowed to work on the report at the same time.
    defaultValue: 20
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    packageName: open-xchange-core
    tags: ["Report","Limit", "Thread"]
  - key: com.openexchange.report.appsuite.threadPriority
    description: |
      The priority that threads, working on the report have. Allowed value range is <code>1</code> - <code>10</code>. <code>1</code> is the lowest, <code>10</code> the highest priority.
    defaultValue: 1
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    packageName: open-xchange-core
    tags: ["Report", "Thread"]           