feature_name: Resource
properties:
    - key: CHECK_RES_UID_FOR_NOT_ALLOWED_CHARS
      description: |
        Specifies whether to check the resource name by using the check in [[CHECK_RES_UID_REGEXP]].
      defaultValue: true
      version: 
      reloadable: false
      configcascadeAware: false
      related: CHECK_RES_UID_REGEXP
      file: Resource.properties
      packageName: open-xchange-admin
      tags: ["Resource"]
    - key: CHECK_RES_UID_REGEXP
      description: |
        Specifies a check to perform for resource names in case [[CHECK_RES_UID_FOR_NOT_ALLOWED_CHARS]] is set to <code>true</code>.
      defaultValue: "[ $@%\\.+a-zA-Z0-9_-]"
      version: 
      reloadable: false
      configcascadeAware: false
      related: CHECK_RES_UID_FOR_NOT_ALLOWED_CHARS
      file: Resource.properties
      packageName: open-xchange-admin
      tags: ["Resource"]
    - key: AUTO_TO_LOWERCASE_UID
      description: |
        Specifies whether to lowercase the uid or not.
      defaultValue: false
      version: 
      reloadable: false
      configcascadeAware: false
      related:
      file: Resource.properties
      packageName: open-xchange-admin
      tags: ["Resource"]