feature_name: RSS
properties:
    - key: com.openexchange.messaging.rss.feed.schemes
      description: |
        Defines the URL schemes that are allowed while adding new RSS feeds. An empty value means all (by URL supported) schemes are allowed.
      defaultValue: http, https, ftp
      version: 7.8.3
      reloadable: false
      configcascadeAware: false
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS"]
    - key: com.openexchange.rss
      description: |
        If set to <code>false</code> disables the rss capability.
      defaultValue: true
      version: 7.2.1
      reloadable: true
      configcascadeAware: true
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS"]
    - key: com.openexchange.messaging.rss
      description: |
        Whether the RSS Messaging Service is available or not.
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS"]
    - key: com.openexchange.messaging.rss.feed.size
      description: |
        Defines the maximum feed size for an RSS feed in bytes.
      defaultValue: 4194304
      version:
      reloadable: true
      configcascadeAware: false
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS", "Limit"]
    - key: com.openexchange.messaging.rss.feed.blacklist
      description: |
        Specifies a black-list for those hosts that are covered by denoted IP range; e.g. 
        <pre>
        com.openexchange.messaging.rss.feed.blacklist=127.0.0.1-127.255.255.255, localhost, internal.domain.org
        </pre>
        An empty value means no black-listing is active.
      defaultValue: 127.0.0.1-127.255.255.255,localhost
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS", "Black List"]
    - key: com.openexchange.messaging.rss.feed.whitelist.ports
      description: |
        Specifies a white-list for such ports that are allowed to connect against when adding/updating a RSS feed.
        No port will always be accepted. 
        An empty value means no white-listing is active.
      defaultValue: 80,443
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: rssmessaging.properties
      packageName: open-xchange-messaging
      tags: ["RSS", "White List"]      