feature_name: Secret
properties:
  - key: com.openexchange.secret.secretSource
    description: |
      Specifies the source for secret (used to decrypt/encrypt user passwords).  
      Possible values:
      <ul>
        <li><code>&lt;password&gt;</code> - Denotes the session's password (also the fall-back to previous handling).</li>
      <li><code>&lt;user-id&gt;</code> - Denotes the user identifier.</li>
      <li><code>&lt;context-id&gt;</code> - Denotes the context identifier.</li>
      <li><code>&lt;random&gt;</code> - Denotes the value specified in property [[com.openexchange.secret.secretRandom]].</li>
      <li><code>&lt;list&gt;</code> - Step-wise trial-and-error with tokens specified in file 'secrets'.</li>
      </ul>
      Literals are surrounded by single-quotes. E.g.:
      <pre>
      com.openexchange.secret.secretSource="&lt;user-id&gt; + '@' + &lt;context-id&gt;"
      </pre>
    defaultValue: "<password>" 
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: secret.properties 
    packageName: open-xchange-core
    tags: ["Secret"] 
  - key: com.openexchange.secret.secretRandom
    description: |
      The random secret token.
    defaultValue:  
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: secret.properties
    tags: ["Secret", "Credential"]      
  - key: com.openexchange.secret.recovery.fast.enabled
    description: |
      Specifies if the special fast crypt token check is enabled or not.

      That mechanism is used to check the validity of user's current secret in a fast manner
      and is used when triggering the "recovery/secret?action=check" call.   
    defaultValue: true  
    version: 
    reloadable: true
    configcascadeAware: true
    related: 
    file: secret.properties 
    packageName: open-xchange-core    
    tags: ["Secret"] 