feature_name: SMTP
feature_description: |
  To differentiate between settings that apply all SMTP accounts or settings that only apply to the primary account
  each property containing the ".primary" suffix allows to specify a value only applicable to the primary account
  by appending the "primary." suffix to properties' common "com.openexchange.smtp." prefix.  
  E.g.
  <pre>
  com.openexchange.smtp.smtpTimeout=50000 
  # specifies 50sec read timeout for every SMTP account  

  com.openexchange.smtp.primary.smtpTimeout=20000 
  # specifies 20sec read timeout for primary-only SMTP account  
  </pre>
properties:
    - key: com.openexchange.smtp.smtpLocalhost
      description: |
        The localhost name that is going to be used on SMTP's HELO or EHLO command.
        The default is set to InetAddress.getLocalHost().getHostName() but if either JDK or name service are not
        configured properly, this routine fails and the HELO or EHLO command is send without a name which
        leads to an error: "501 HELO requires domain address".
        The value <code>null</code> falls back to InetAddress.getLocalHost().getHostName() which works in most cases.
      defaultValue: null
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Host"]
    - key: com.openexchange.smtp.smtpAuthentication
      description: |
        Enable/disable SMTP Authentication.
      defaultValue: true
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.smtpAuthEnc
      description: |
        Define the encoding for SMTP authentication.
      defaultValue: UTF-8
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.setSMTPEnvelopeFrom
      description: |
        Defines if SMTP header ENVELOPE-FROM should be explicitly set to
        user's primary email address or not.
        Applies only to primary SMTP account; considered as <code>false</code> for every external SMTP account.
      defaultValue: false
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.smtpTimeout
      description: |
        Define the socket read timeout value in milliseconds. A value less than
        or equal to zero is infinite timeout.
      defaultValue: 50000
      version: 
      reloadable: true
      configcascadeAware: true
      related: mail.smtp.timeout
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Timeout"]
    - key: com.openexchange.smtp.smtpConnectionTimeout
      description: |
        Define the socket connect timeout value in milliseconds. A value less
        or equal to zero is infinite timeout.
      defaultValue: 10000
      version: 
      reloadable: true
      configcascadeAware: true
      related: mail.smtp.connectiontimeout
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Timeout"]
    - key: com.openexchange.smtp.logTransport
      description: |
        Specifies whether a transported message shall be logged providing "Message-Id" header, login, and SMTP server information.
        Applies only to primary SMTP account; considered as <code>false</code> for every external SMTP account.
      defaultValue: false
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.ssl.protocols
      description: |
        Specifies the SSL protocols that will be enabled for SSL connections. The property value is a whitespace separated list of tokens.
      defaultValue: 
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.ssl.ciphersuites
      description: |
        Specifies the SSL cipher suites that will be enabled for SSL connections. The property value is a whitespace separated list of tokens.
        
        Check "http://&lt;ox-grizzly-hostname&gt;:&lt;ox-grizzly-port&gt;/stats/diagnostic?param=ciphersuites" to check available cipher suites.
        
        If left empty the current JVM's default SSL cipher suite is used.
      defaultValue: 
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.sendPartial
      description: |
        Whether partial send is allowed or message transport is supposed to be aborted.
      defaultValue: false
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]

    - key: com.openexchange.smtp.primary.smtpLocalhost
      description: |
        The localhost name that is going to be used by the primary account on SMTP's HELO or EHLO command.
        The default is set to InetAddress.getLocalHost().getHostName() but if either JDK or name service are not
        configured properly, this routine fails and the HELO or EHLO command is send without a name which
        leads to an error: "501 HELO requires domain address".
        The value <code>null</code> falls back to InetAddress.getLocalHost().getHostName() which works in most cases.
      defaultValue: null
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Host"]
    - key: com.openexchange.smtp.primary.smtpAuthentication
      description: |
        Enable/disable SMTP Authentication for the primary account.
      defaultValue: true
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.primary.smtpAuthEnc
      description: |
        Defines the encoding used by the primary account for SMTP authentication.
      defaultValue: UTF-8
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.primary.smtpTimeout
      description: |
        Define the socket read timeout value in milliseconds for the primary account. A value less than
        or equal to zero is infinite timeout.
      defaultValue: 50000
      version: 
      reloadable: true
      configcascadeAware: true
      related: mail.smtp.timeout
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Timeout"]
    - key: com.openexchange.smtp.primary.smtpConnectionTimeout
      description: |
        Define the socket connect timeout value in milliseconds for the primary account. A value less
        or equal to zero is infinite timeout.
      defaultValue: 10000
      version: 
      reloadable: true
      configcascadeAware: true
      related: mail.smtp.connectiontimeout
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP", "Timeout"]
    - key: com.openexchange.smtp.primary.ssl.protocols
      description: |
        Specifies the SSL protocols that will be enabled for SSL connections for the primary account. The property value is a whitespace separated list of tokens.
      defaultValue: 
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.primary.ssl.ciphersuites
      description: |
        Specifies the SSL cipher suites that will be enabled for SSL connections for the primary account. The property value is a whitespace separated list of tokens.
        
        Check "http://&lt;ox-grizzly-hostname&gt;:&lt;ox-grizzly-port&gt;/stats/diagnostic?param=ciphersuites" to check available cipher suites.
        
        If left empty the current JVM's default SSL cipher suite is used.
      defaultValue: 
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
    - key: com.openexchange.smtp.primary.sendPartial
      description: |
        Whether partial send is allowed or message transport is supposed to be aborted for the primary account.
      defaultValue: false
      version: 
      reloadable: true
      configcascadeAware: true
      related: 
      file: smtp.properties
      packageName: open-xchange-imap
      tags: ["Mail","SMTP"]
