feature_name: Soap
properties:
    - key: com.openexchange.soap.cxf.baseAddress
      description: |
        Specifies the base address for published end points; e.g. "http://www.myserver.com/myservices"
        An empty value means that the running machine's address is used.
      defaultValue:
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: soap-cxf.properties
      packageName: open-xchange-soap-cxf
      tags: ["SOAP"]
    - key: com.openexchange.soap.cxf.hideServiceListPage
      description: |
        Specifies whether to hice service list page.
      defaultValue: false
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: soap-cxf.properties
      packageName: open-xchange-soap-cxf
      tags: ["SOAP"]
    - key: com.openexchange.soap.cxf.entityExpansionLimit
      description: |
        Java platform limits the number of entity expansions that are allowed for a single XML document.
        Default is <code>128000</code>, which is considered to be a pretty large number for any real life application.
        
        However, if any application does need to have a higher limit, this property (which maps to 'entityExpansionLimit' system property)
        can be increased to the desired size. Setting it to <code>0</code> (zero) means unlimited.
      defaultValue: 128000
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: soap-cxf.properties
      packageName: open-xchange-soap-cxf
      tags: ["SOAP", "Limit"]
    - key: com.openexchange.soap.cxf.disableAddressUpdates
      description: |
        This is a workaround for the known side-effect in CXF 2.7.x described in CXF-5737 issue ([[https://issues.apache.org/jira/browse/CXF-5737]])
        The endpoint address gets manipulating after accessing it via multiple aliases.
        This is disabled by default in the upcoming versions of CXF.
      defaultValue: true
      version: 
      reloadable: false
      configcascadeAware: false
      related: 
      file: soap-cxf.properties
      packageName: open-xchange-soap-cxf
      tags: ["SOAP", "Limit"]