feature_name: Subscribe
properties:
    - key: com.openexchange.subscribe.autorun
      description: |
        Defines whether subscriptions should be run automatically on login, if a given interval has elapsed.
        The intervals default to one day, but can be configured individually by subscription type
        in the subscription source specific configuration files.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: subscribe.properties
      packageName: open-xchange-core
      tags: ["Subscribe"]
    - key: com.openexchange.subscribe.google.calendar.pageSize
      description: |
        Defines the amount of events to fetch in a single request.
      defaultValue: 25
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: googlesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Google", "Calendar", "Subscribe"]
    - key: com.openexchange.subscribe.google.contact.pageSize
      description: |
        Defines the amount of contacts to fetch in a single request.
      defaultValue: 25
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: googlesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Google", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.google.calendar.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for Google calendars.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: googlesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Google", "Calendar", "Subscribe"]
    - key: com.openexchange.subscribe.google.contact.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for Google contacts.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: googlesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Google", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.linkedin
      description: |
        Enable/disable LinkedIn subscribe service.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: linkedinsubscribe.properties
      packageName: open-xchange-linkedin
      tags: ["LinkedIn", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.linkedin.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for LinkedIn.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: linkedinsubscribe.properties
      packageName: open-xchange-linkedin
      tags: ["LinkedIn", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.mslive.contact.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for MS Live.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: mslivesubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["MS Live Connect", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.microformats.contacts.http
      description: |
        Enables / disables the microformats contacts subscription.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.microformats.infostore.http
      description: |
        Enables / disables the microformats infostore subscription.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Infostore", "Subscribe"]
    - key: com.openexchange.subscribe.microformats.contacts.http.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for Microformats.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.microformats.infostore.http.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for the microformats infostore.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Infostore", "Subscribe"]
    - key: com.openexchange.subscribe.microformats.allowedHosts
      description: |
        Optionally specifies the list of accepted host names allowed being subscribed.
        If left empty, there is no restriction for such subscriptions.
        Otherwise non-matching host names are rejected. 
      defaultValue:
      version:
      reloadable: true
      configcascadeAware: false
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Subscribe", "White List"]
    - key: com.openexchange.subscribe.microformats.createModifyEnabled
      description: |
        Enabled/disables the possibility to create/modify subscriptions.
        Should be set to false, because the new sharing module is supposed to be used and this module is considered as deprecated.
      defaultValue: false
      version:
      reloadable: true
      configcascadeAware: false
      related: 
      file: microformatSubscription.properties
      packageName: open-xchange-subscribe
      tags: ["Microformats", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.yahoo
      description: |
        Enable/disable Yahoo subscribe service.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: yahoosubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Yahoo", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.yahoo.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for Yahoo.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: yahoosubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Yahoo", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.xing
      description: |
        Enable/disable XING subscribe service.
      defaultValue: true
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: xingsubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Xing", "Contact", "Subscribe"]
    - key: com.openexchange.subscribe.socialplugin.xing.autorunInterval
      description: |
        Defines the subscription refresh autorun interval for XING.
      defaultValue: 1d
      version:
      reloadable: true
      configcascadeAware: true
      related: 
      file: xingsubscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Xing", "Contact", "Subscribe"]