feature_name: Feature XYZ
feature_description: |
  This pages describes feature XYZ
properties:
    - key: c.o.some.property
      description: |
        line1
        line2
        line3
      defaultValue: true
      version: 7.8.3
      reloadable: true
      configcascadeAware: false
      related: c.o.some.property
      file:
      packageName: open-xchange-core
      tags: []
    - key: c.o.some.property2
      description: |
        line1
        line2
      defaultValue: true
      version: 7.8.0
      reloadable: true
      configcascadeAware: true
      related: ["c.o.some.property.1","c.o.some.property.2"]
      file: somefile.properties
      packageName: open-xchange-packageB
      tags: ["tagA","tagB"]