feature_name: Threadpool
properties:
    - key: com.openexchange.threadpool.corePoolSize
      description: |
        The number of threads to keep in the pool, even if they are idle.
        If unsure follow this rule: Size = Number of CPUs + 1.
      defaultValue: 3
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]
    - key: com.openexchange.threadpool.prestartAllCoreThreads
      description: |
        Starts all core threads, causing them to idly wait for work.
        This overrides the default policy of starting core threads only when new tasks are executed. 
      defaultValue: true
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]
    - key: com.openexchange.threadpool.maximumPoolSize
      description: |
        The maximum number of threads to allow in the pool.
        The max. integer value of 2^31 - 1 is considered as unlimited max. number of threads.
      defaultValue: 2147483647
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Limit", "Thread"]
    - key: com.openexchange.threadpool.keepAliveTime
      description: |
        When the number of threads is greater than the core, this is the maximum
        time (in milliseconds) that excess idle threads will wait for new tasks before terminating.
      defaultValue: 60000
      version:
      reloadable: false
      configcascadeAware: false
      related: 
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Limit", "Thread"]
    - key: com.openexchange.threadpool.workQueue
      description: |
        The queue type to use for holding tasks before they are executed. This queue will
        hold only the tasks submitted by the execute method.  
        Supported values: <code>synchronous</code> and <code>linked</code>

        A synchronous queue is an appropriate choice when [[com.openexchange.threadpool.maximumPoolSize]]
        is unlimited and possible rejection of tasks is allowed. A synchronous queue has no capacity,
        it rather acts as a direct hand-off of tasks to an already waiting worker thread and will deny
        the task if there is no further worker thread to process the task.

        A linked queue is an appropriate choice when [[com.openexchange.threadpool.maximumPoolSize]]
        is limited and rejection of tasks is prohibited. A linked queue has a (fixed) capacity to store
        submitted tasks which have to wait for a worker thread to become ready.
      defaultValue: synchronous
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.threadpool.maximumPoolSize
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]
    - key: com.openexchange.threadpool.workQueueSize
      description: |
        The size of the work queue. Zero means unlimited size.

        Note:  
        If this property is set to a value greater than zero, property [[com.openexchange.threadpool.workQueue]]
        is implicitly set to <code>linked</code> to accomplish a fixed-size work queue.
      defaultValue: 0
      version:
      reloadable: false
      configcascadeAware: false
      related: com.openexchange.threadpool.workQueue
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]
    - key: com.openexchange.threadpool.blocking
      description: |
        Enable/disable blocking behavior. A blocking behavior means that caller is blocked until space becomes available in working queue.
        This is useful for installation with limited capacities concerning max. number of threads and a bounded blocking work queue.
      defaultValue: false
      version:
      reloadable: false
      configcascadeAware: false
      related:
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]
    - key: com.openexchange.threadpool.refusedExecutionBehavior
      description: |
        The default behavior to obey when execution is blocked because the thread bounds and queue
        capacities are reached.  
        Supported values:
          <ul>
           <li><code>abort</code> - Aborts execution by throwing an appropriate exception to the caller.</li>
           <li><code>caller-runs</code> - The caller is considered to run the task if thread pool is unable to do so.</li>
           <li><code>discard</code> - The task is silently discarded. No exception is thrown.</li>
          </ul>
      defaultValue: abort
      version:
      reloadable: false
      configcascadeAware: false
      related:
      file: threadpool.properties
      packageName: open-xchange-core
      tags: ["Threadpool", "Thread"]