type: object
properties:
  test:
    type: string
    description: The name of the test, see [Possible tests](#possible-tests).
  comparison:
    type: array
    description: An array of the valid comparison types for this test, see [Possible comparisons](#possible-comparisons).
    items:
      type: string