type: object
properties:
  tests:
    type: array
    description: Array of available test-objects.
    items:
      $ref: "#/definitions/MailFilterConfigTest"
  actioncommands:
    type: array
    description: Array of available action commands.
    items:
      type: string
  capabilities:
    type: array
    description: Array of supported imap capabilities
    items:
      type: string
