/advertisement/v1/config/name:
  put:
    operationId: putAdvertisementByName
    tags:
      - Advertisement
    summary: Sets an advertisement configuration for a given user by name
    parameters:
      - 
        name: name
        in: query
        description: The user's login name
        required: true
        type: string
      - 
        name: contextId
        in: query
        description: The context id
        required: true
        type: integer
        format: int64
      -
        name: body
        in: body
        description: JSONObject describing the advertisement configuration
        required: true
        schema:
          type: string

    responses:
      200:
        description: The configuration result
      400:
        description: Bad request, response contains error message.
      401:
        description: Not authorized

  delete:
    operationId: deleteAdvertisementByName
    tags:
      - Advertisement
    summary: Remove the current configuration for the user
    parameters:
      - 
        name: name
        in: query
        description: The user's login name
        required: true
        type: string
      - 
        name: contextId
        in: query
        description: The context id
        required: true
        type: integer
        format: int64

    responses:
      200:
        description: The configuration result
      400:
        description: Bad request, response contains error message.
      401:
        description: Not authorized
